### ISSUE TITLE
update in html website

### ISSUE THREAD

**Issue by scorcism** [scorcism/website-using-js#2]
**update the in html website** 

- Responsive
- More color gradient
- More components
- etc

**Comment by y4sssh** [comment]
I Would like to work on this

**Comment by scorcism** [comment]
Yes sure go for it, but 1st show me the design you are going to change to

**Comment by y4sssh** [comment]
Which design?

**Comment by scorcism** [comment]
the design you will be using as a reference to change the HTMl website

**Comment by y4sssh** [comment]
Hey Bro can Remove me from this project 
I am not getting time from the project

**Comment by scorcism** [comment]
okay no worries. Thank You
