### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by scorcism** [scorcism/website-using-js#5]
- Make the website responsive
- In HTML website is only to be made responsive

**Comment by raquelmangual** [comment]
I will take a look and let you know if I can help.

**Comment by raquelmangual** [comment]
Do you want the columns to stack on smaller screens?

**Comment by scorcism** [comment]
@raquelocasio anything will work which can make website attractive and responsive.

**Comment by raquelmangual** [comment]
Ok I can do this. Please assign this task to me. Thanks.

**Comment by scorcism** [comment]
yes done.
All the best.

**Comment by raquelmangual** [comment]
Do you mind if I redo some of the HTML?

**Comment by scorcism** [comment]
No, you can cutomize as per your design
